/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 model.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/model.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.2, 0.24, 0.53]} rotation={[Math.PI / 2, 0, -0.06]}>
        <mesh geometry={nodes.End_Pieces.geometry} material={materials['Clout Goggles Sunglasses']} />
        <mesh geometry={nodes.Hinges.geometry} material={materials['Clout Goggles Sunglasses']} />
      </group>
      <mesh geometry={nodes.Plane.geometry} material={materials['Black Plastic']} position={[0.07, 0.14, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.34} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Fine Gold']} position={[-1.03, 0.19, -0.01]} rotation={[Math.PI / 2, 0, 0]} scale={0.07} />
      <mesh geometry={nodes.Text.geometry} material={materials['Fine Gold']} position={[-0.24, -1.69, 0.01]} rotation={[Math.PI / 2, 0, 0]} scale={0.51} />
      <mesh geometry={nodes.Plane002.geometry} material={materials['Material.001']} position={[-0.41, 1.67, 0.02]} rotation={[Math.PI / 2, 0, 0]} scale={0.05} />
      <mesh geometry={nodes.Circle.geometry} material={materials['Fine Gold']} position={[-0.41, 1.68, -0.66]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Plane004.geometry} material={materials.Material} position={[1.45, 0.53, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.06} />
      <mesh geometry={nodes.Plane003.geometry} material={materials['Fine Gold']} position={[1.44, 0.49, 0.01]} rotation={[Math.PI / 2, 0, 0]} scale={0.04} />
      <mesh geometry={nodes.Plane005.geometry} material={materials['Fine Gold']} position={[1.44, 0.32, 0.01]} rotation={[Math.PI / 2, 0, 0]} scale={0.04} />
      <mesh geometry={nodes.Plane008.geometry} material={materials['Fine Gold']} position={[1.44, 0.16, 0.01]} rotation={[Math.PI / 2, 0, 0]} scale={0.04} />
      <mesh geometry={nodes.Plane009.geometry} material={materials['Fine Gold']} position={[1.25, 0.49, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={0.1} />
      <mesh geometry={nodes.Plane010.geometry} material={materials['Fine Gold']} position={[0.07, 0.14, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.34} />
      <mesh geometry={nodes.Plane011.geometry} material={materials['Black murble']} position={[0.14, -1.01, -0.07]} rotation={[Math.PI / 2, 0, 0]} scale={0.33} />
      <mesh geometry={nodes.Plane012.geometry} material={materials.Material} position={[0.15, -1, -0.09]} rotation={[Math.PI / 2, 0, 0]} scale={0.33} />
      <mesh geometry={nodes.Circle001.geometry} material={materials['Fine Gold']} position={[-2.95, 2.09, -0.66]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Plane006.geometry} material={materials.Material} position={[-1.1, 0.94, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.06} />
      <mesh geometry={nodes.Plane007.geometry} material={materials['Fine Gold']} position={[-1.1, 0.9, 0.01]} rotation={[Math.PI / 2, 0, 0]} scale={0.04} />
      <mesh geometry={nodes.Plane013.geometry} material={materials['Fine Gold']} position={[-1.1, 0.74, 0.01]} rotation={[Math.PI / 2, 0, 0]} scale={0.04} />
      <mesh geometry={nodes.Plane014.geometry} material={materials['Fine Gold']} position={[-1.1, 0.58, 0.01]} rotation={[Math.PI / 2, 0, 0]} scale={0.04} />
      <mesh geometry={nodes.Plane015.geometry} material={materials['Fine Gold']} position={[-1.3, 0.91, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={0.1} />
      <mesh geometry={nodes.Circle002.geometry} material={materials['Fine Gold']} position={[-2.95, 0.98, -0.66]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Plane016.geometry} material={materials.Material} position={[-1.1, -0.17, 0.01]} rotation={[Math.PI / 2, 0, 0]} scale={0.06} />
      <mesh geometry={nodes.Plane017.geometry} material={materials['Fine Gold']} position={[-1.1, -0.21, 0.01]} rotation={[Math.PI / 2, 0, 0]} scale={0.04} />
      <mesh geometry={nodes.Plane018.geometry} material={materials['Fine Gold']} position={[-1.1, -0.37, 0.01]} rotation={[Math.PI / 2, 0, 0]} scale={0.04} />
      <mesh geometry={nodes.Plane019.geometry} material={materials['Fine Gold']} position={[-1.1, -0.54, 0.01]} rotation={[Math.PI / 2, 0, 0]} scale={0.04} />
      <mesh geometry={nodes.Plane020.geometry} material={materials['Fine Gold']} position={[-1.29, -0.21, -0.03]} rotation={[Math.PI / 2, 0, 0]} scale={0.1} />
      <mesh geometry={nodes.Plane021.geometry} material={materials['Fine Gold']} position={[0.07, 0.14, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.34} />
      <mesh geometry={nodes.Plane022.geometry} material={materials.chrome} position={[0.07, 0.14, -0.05]} rotation={[Math.PI / 2, 0, 0]} scale={0.34} />
      <mesh geometry={nodes.Plane023.geometry} material={materials.chrome} position={[0.07, 0.14, -0.09]} rotation={[Math.PI / 2, 0, 0]} scale={0.33} />
      <mesh geometry={nodes.Plane024.geometry} material={materials['Space Universe Galaxy']} position={[0.28, 0.34, -0.09]} rotation={[Math.PI / 2, 0, 0]} scale={1.34} />
      <mesh geometry={nodes.Suzanne.geometry} material={materials['Fine Gold']} position={[0.18, 0.17, 0.24]} scale={0.38} />
    </group>
  )
}

useGLTF.preload('/model.gltf')
